name: Dev build and publish Docker distributions to Github Container Registry ghcr.io
on:
  push:
    branches-ignore:
      - master
      - version-*

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/dev-java-docker-publish.yml@th2-4135-trivy-workflow
    with:
      docker-username: ${{ github.repository_owner }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
