name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
    - master
    paths:
    - gradle.properties
    - package_info.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Read version from gradle.properties
      id: read_property
      uses: BrycensRanch/read-properties-action@v1.0.3
      with:
        file: ./gradle.properties
        property: release_version
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.read_property.outputs.value }}
        provenance: false
        build-args: |
          release_version=${{ steps.read_property.outputs.value }}
