name: Build and publish Python distributions to PyPI

on:
  push:
    branches:
    - master
    paths:
    - package_info.json

jobs:
  build-n-publish:
    name: Build and Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Build package
      run: |
        pip install -r requirements.txt
        python setup.py generate
        python setup.py sdist
    # - name: Publish distribution to Test PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.TEST_PYPI_PASSWORD }}
    #     repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
        repository_url: https://upload.pypi.org/legacy/
