name: Scan licenses and vulnerabilities in java project

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      javaVersion:
        required: false
        type: string
        default: '11'
      javaVendor:
        required: false
        type: string
        default: 'zulu'
      # Vulnerability scanning
      scanner-enabled:
        required: false
        type: boolean
        default: true
        description: 'Whether vulnerabilities and license scanning are enabled'
      multiproject:
        required: false
        type: boolean
        default: false
        description: 'false for dependencyCheckAnalyze, true for dependencyCheckAggregate'
    secrets:
      nvd-api-key:
        required: false
        description: 'API key to access NVD database'
      cisa-domain:
        required: false
        description: 'Cybersecurity and Infrastructure Security Agency domain'
      cisa-user:
        required: false
        description: 'Cybersecurity and Infrastructure Security Agency user'
      cisa-password:
        required: false
        description: 'Cybersecurity and Infrastructure Security Agency password'
        
jobs:
  prebuild-job:
    name: Prebuild Job
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-dev-workflow.yml@main
    with:
        runsOn: ${{ inputs.runsOn }}

  owasp-scan:
    if: inputs.scanner-enabled
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main
    with:
      multiproject: ${{ inputs.multiproject }}
      javaVersion: ${{ inputs.javaVersion }}
      javaVendor: ${{ inputs.javaVendor }}
    secrets:
      nvd-api-key: ${{ secrets.nvd-api-key }}
      cisa-domain: ${{ secrets.cisa-domain }}
      cisa-user: ${{ secrets.cisa-user }}
      cisa-password: ${{ secrets.cisa-password }}

  license-check:
    if: inputs.scanner-enabled
    uses: th2-net/.github/.github/workflows/license_check.yml@main
    needs: [prebuild-job]
    with:
      version: ${{ needs.prebuild-job.outputs.version }}