name: Run Python matrix licenses check


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Full version of distributive, with branch name etc.'
      matrix-python-versions:
        required: false
        type: string
        default: "['3.9', '3.10', '3.11']"
        description: 'list of python versions in JSON format'
      matrix-os:
        required: false
        type: string
        default: "['ubuntu-latest']"
        description: 'list of operation systems JSON format'

jobs:
  matrix-license-check:
    name: Run matrix licenses check
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.matrix-python-versions) }}
        os: ${{ fromJson(inputs.matrix-os) }}
    uses: th2-net/.github/.github/workflows/python-license-check.yml@main
    with:
      version: ${{ inputs.version }}
      python-version: ${{ matrix.python-version }}
      runsOn: ${{ matrix.os }}