name: Python matrix style check


on:
  workflow_call:
    inputs:
      matrix-python-versions:
        required: false
        type: string
        default: "['3.9', '3.10', '3.11']"
        description: 'list of python versions in JSON format'
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  matrix-mypy-style-check:
    name: Run matrix MyPy style check
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.matrix-python-versions) }}
    uses: th2-net/.github/.github/workflows/python-style-check-mypy.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runsOn: ${{ inputs.runsOn }}

  matrix-flake8-style-check:
    name: Run matrix Flake8 style check
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.matrix-python-versions) }}
    uses: th2-net/.github/.github/workflows/python-style-check-flake8.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runsOn: ${{ inputs.runsOn }}