name: Prebuild Compound Dev Java Workflow


on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      project-path:
        required: false
        type: string
        default: '.'
        description: 'relative path to the project to extract version'

    outputs:
      version:
        description: "Generated version of the image"
        value: ${{ jobs.prebuild-job.outputs.version }}
      versionNumber:
        description: "Number of the version"
        value: ${{ jobs.prebuild-job.outputs.versionNumber }}
      versionSuffix:
        description: "The suffix for the version with current branch, commit hash and SNAPSHOT suffix"
        value: ${{ jobs.prebuild-job.outputs.versionSuffix }}

jobs:
  prebuild-job:
    name: Pre-build steps for project ${{ inputs.project-path }}
    runs-on: ${{ inputs.runsOn }}
    outputs:
      version: ${{ steps.release_ver.outputs.value }}
      versionNumber: ${{ steps.ver.outputs.release_version }}
      versionSuffix: ${{ steps.version_suffix.outputs.value }}

    steps:
      - uses: actions/checkout@v4
      - name: Get branch name
        id: branch
        # '#refs/*/' is used to remove prefix like `refs/heads/`
        # 'sed 's#/#_#g' is used to replace '/' by '_'. This transformation is required because '/' char isn't allowed in Docker image tag
        run: echo "branch_name=$(echo "${GITHUB_REF#refs/*/}" | sed 's#/#_#g')" >> $GITHUB_OUTPUT
      - name: Get SHA of the commit
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get release_version
        id: ver
        uses: BrycensRanch/read-properties-action@v1.0.4
        with:
          file: ${{ inputs.project-path }}/gradle.properties
          property: release_version
      - name: Build custom release version
        id: release_ver
        run: echo "value="${{ steps.ver.outputs.release_version }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-${{ steps.sha.outputs.sha_short }}"" >> $GITHUB_OUTPUT
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}
      - name: Build version suffix
        id: version_suffix
        run: echo value="${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-${{ steps.sha.outputs.sha_short }}-SNAPSHOT" >> $GITHUB_OUTPUT
      - name: Show version suffix
        run: echo ${{ steps.version_suffix.outputs.value }}

