name: Get package_version from package_info.json

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: ubuntu-latest
      project-path:
        required: false
        type: string
        default: '.'
        description: 'relative path to the project to extract version'
    outputs:
      version:
        description: "package_version from package_info.json"
        value: ${{ jobs.get-package-version.outputs.version }}

jobs:
  get-package-version:
    name: 'Get package_version'
    runs-on: ${{ inputs.runsOn }}
    outputs:
      version: ${{ steps.show-version.outputs.package-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check Poetry file existence
        id: check-poetry-file
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.project-path }}/pyproject.toml
      - name: Install Poetry
        if: steps.check-poetry-file.outputs.files_exists == 'true'
        uses: snok/install-poetry@v1
      - name: Get package_version value from package_info.json
        if: steps.check-poetry-file.outputs.files_exists == 'false'
        id: package-version-from-package-info
        uses: notiz-dev/github-action-json-property@release
        with:
          path: ${{ inputs.project-path }}/package_info.json
          prop_path: package_version
      - name: Get package_version value from Poetry
        if: steps.check-poetry-file.outputs.files_exists == 'true'
        id: package-version-from-poetry
        run: echo "package-version=$(poetry -C ${{ inputs.project-path }} version -s)" >> $GITHUB_OUTPUT
      - name: Show package_version value 
        id: show-version
        run: |
          if [[ "${{ steps.check-poetry-file.outputs.files_exists }}" == 'true' ]]; then
            echo "From Poetry"
            echo "package-version=${{ steps.package-version-from-poetry.outputs.package-version }}" >> $GITHUB_OUTPUT
            echo ${{ steps.package-version-from-poetry.outputs.package-version }}
          else
            echo "From package_info.json"
            echo "package-version=${{ steps.package-version-from-package-info.outputs.prop }}" >> $GITHUB_OUTPUT
            echo ${{ steps.package-version-from-package-info.outputs.prop }}
          fi