name: Trivy scan Docker image for vulnerable dependencies and publish results to security tab

on:
  workflow_call:
    inputs:
      image-path:
        required: true
        type: string
      target:
        required: false
        type: string
        default: 'os,library'
        description: 'What Trivy will scan: image, library or both'
      sensitivity:
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'
        description: 'Adjusting the Scanner Sensitivity'
      exitCode:
        required: false
        type: string
        default: '0'
        description: 'Exit code when specified vulnerabilities are found (1 for fail, 0 for ignore)'
      ignoreUnfixed:
        required: false
        type: boolean
        default: false
        description: 'Ignore vulnerabilities that are impossible to fix at the moment'

jobs:
  trivy-scan-job:
    runs-on: ubuntu-latest
    # dependabot doesn't publish artifacts than docker image can't be verified by trivy
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Show scanning target
        run: echo ${{ inputs.image-path }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-path }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.sensitivity }}
          exit-code: ${{ inputs.exitCode }}
          ignore-unfixed: ${{ inputs.ignoreUnfixed }}
          vuln-type: ${{ inputs.target }}
          timeout: 20m0s
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'